### ISSUE TITLE
whta's the meaning of 'adaptive-scale' argument?

### ISSUE THREAD

**Issue by gotobelieve** [LiyuanLucasLiu/Transformer-Clinic#1]
hi, I have read your original paper, and get trouble when I want to replicate the experiment, could you please explain the meaning of  'adaptive-scale' argument in options.py？

**Comment by LiyuanLucasLiu** [comment]
It's a debug argument to verify that our initialization can control the output variance to what we want. This parameter is not used in our experiments. It will be deleted later.
