### ISSUE TITLE
IWSLT'14 Results

### ISSUE THREAD

**Issue by villmow** [LiyuanLucasLiu/Transformer-Clinic#12]
Hi, very nice paper, I like it! I have a question regarding your results on IWSLT'14. Are these values tokenized BLEU on `dev` or `test` set?

Dataset IWSLT’14 De-En 
Enc #–Dec # 6L–6L (small) 
Post-LN **35.64** ± 0.23 
Pre-LN **35.50** ± 0.04 
Admin **35.67** ± 0.15

**Comment by LiyuanLucasLiu** [comment]
Thanks for your attention, glad you enjoy the paper : -)
The results on IWSLT'14 are on the `test` set.
