### ISSUE TITLE
Question about the adaptive optimizer

### ISSUE THREAD

**Issue by chenwydj** [LiyuanLucasLiu/Transformer-Clinic#19]
Thanks for this great work!

I failed to find more details about the adaptive optimizer mentioned in the paper. Could you point me any reference or github link about this adaptive optimizer?

Thank you!

**Comment by LiyuanLucasLiu** [comment]
Hi thanks for reaching out. 
In the paper, we use adaptive optimizer to refer a class of optimizers including Adam, Adamax, RMSProp, RAdam, etc. In our experiments, we are using [RAdam](https://github.com/LiyuanLucasLiu/RAdam) as the optimizer.
