### ISSUE TITLE
Is the "attention_ratio_change" and "fc_ratio_change" trainable or not?

### ISSUE THREAD

**Issue by gotobelieve** [LiyuanLucasLiu/Transformer-Clinic#3]
hi, according to the code in the transformer_layer.py, these two variable are trainable parameters, I'm not sure what's reason behind this setting?

**Comment by LiyuanLucasLiu** [comment]
Any specific reason for making these parameters non-trainable? I believe their computation overheads should be negligible. Typically all models parameters are set to be trainable by default and I'm not sure whether fixing these paramteres would lead to a performance drop.

**Comment by gotobelieve** [comment]
Thanks, I will try it later.
