### ISSUE TITLE
How to make sure that only performing one step forward pass in profiling phase?

### ISSUE THREAD

**Issue by ZhenYangIACAS** [LiyuanLucasLiu/Transformer-Clinic#8]
Hello, I want to figure out how do you make sure that only performing one step forward pass in profiling phase in your code? Since the running scripts for profiling and training are the same, I cannot find where do you set the limitation for profiling.

**Comment by LiyuanLucasLiu** [comment]
Hi thanks for asking: -)
Their scripts are not the same (`--init-type adaptive` is changed to `--init-type adaptive-profiling` for profiling).  
The limitation is set at: 
https://github.com/LiyuanLucasLiu/Transformer-Clinic/blob/a302132c52084d730aca5822abb58228a04b6bb8/fairseq/fairseq/tasks/fairseq_task.py#L265
